name: test

on:
  push:
    branches:
      - "schedule"

jobs:
  run-help:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "npm"
          cache-dependency-depth: log-analytics-cli/package-lock.json

      - name: Install deps
        working-directory: log-analytics-cli
        run: |
          if [ -f package-lock.json ]; then
            npm ci
          else
            npm install
          fi

      - name: Run cli
        working-directory: log-analytics-cli
        run: npm run analytics -- --help
